# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60808a6b186537c707809c5245654d2f"
application_url = "https://gel-malpractice-illness-blade.trycloudflare.com"
embedded = true
name = "embroidery"
handle = "embroidery-3"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms"

[auth]
redirect_urls = [
  "https://gel-malpractice-illness-blade.trycloudflare.com/auth/callback",
  "https://gel-malpractice-illness-blade.trycloudflare.com/auth/shopify/callback",
  "https://gel-malpractice-illness-blade.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "wiro-trial-piece-chirag.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
